
api:
  stripe:
    key: pk_test_51NfN7RJdkwpdiEIiViPOq1vCZMBeduWLq02jAELt0uH23HmfQvzJsbPX8mw9Q1LpJbVgsnkTb4nF9dQe1h1wFbbj000FIwBjM6

server:
  port: 9095
  servlet:
    context-path: /api/integration

spring:
  sendgrid:
    api-key: sk_test_51NfN7RJdkwpdiEIian6J96f6s61ehWRSLQ9747AjfxOVK7AvyNTb8NdeTWMFn5MV2pnpnOgxrgWXTv3iT41VNvTl006IEHfeEk

  datasource:
    url: jdbc:mysql://localhost:3306/paymentsdb
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

